version: 1
disable_existing_loggers: False
formatters:
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s: %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: brief
    stream: ext://sys.stdout
    filters: [console_only]
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: ''
    mode: w
    filters: [file_only] 
loggers:
  production:
    level: DEBUG
    handlers: [console, file]
    propagate: no
filters:
  console_only:
    (): placeholder.ConsoleOnlyFilter 
  file_only:
    (): placeholder.FileOnlyFilter 