name: " Get and Cache dependencies"
description: "Get the dependencies and cache them"
inputs:
  caching:
    description: "whether to cache dependencies or not"
    required: false
    default: "true"
outputs:
  used-cache:
    description: "Whether the cache was used"
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      if: inputs.caching == 'true'
      id: cache
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip" # Use built-in pip cache

    - name: Install dependencies
      id: install
      if: steps.setup.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        echo "cache='${{ inputs.caching }}'">>$GITHUB_OUTPUT
      shell: bash
